### ISSUE TITLE
Fix "None" labels in content model OWL file

### ISSUE THREAD

**Issue by tudorache** [who-icatx/whofic-models#13]
In the generated ontologymodel.owl, there are a few classes with name None, and also property values None:

<img width="899" alt="image" src="https://github.com/who-icatx/whofic-models/assets/2709502/42d87702-d4e0-4b28-b864-672d8c673def">

**Comment by samsontu** [comment]
I think this is a View issue. The name of the selected class is :WHOFICEntityModel.

**Comment by tudorache** [comment]
No, this is actually part of the OWL file. Look for "None" string in the contentmodel.owl. It is probably generated by LinkML

<img width="618" alt="image" src="https://github.com/who-icatx/whofic-models/assets/2709502/24ba8826-0261-4025-984c-5d00ab70ff2d">
