### ISSUE TITLE
Object property hierarchy in whofic-2024-01-24.owl needs to be re-organized. 

### ISSUE THREAD

**Issue by samsontu** [who-icatx/whofic-models#16]
Some properties at the top-level of the object property hierarchy, such as "counterpart" probably should be subproperties of "externalCauseDimensions." Others, like "fractureOpenOrClosed," should be subproperties of "injuryQualifier." Also, it's probably a good idea to organize the post-coordination axes of different classifications in their own hierarchies.

**Comment by csnyulas** [comment]
Indeed. This is important. Can be done with the LinkML model directly? I assign this issue to you, @samsontu, please feel free to reassign it if you think someone else should deal with it.

**Comment by csnyulas** [comment]
I guess you already did this reorganization in https://github.com/who-icatx/whofic-models/commit/9bca57d6f893b8191eec5ed204c4fd352cd5e248, and you mean than the content model used in the migrated ICD content should be also adjusted (which can be done perhaps by @tudorache). Please clarify.

**Comment by samsontu** [comment]
I will do the reorganization in the next iteration. My guess is that such reorganization won't affect the migration of the content.

**Comment by samsontu** [comment]
Close issue as the post-coordination axes had been re-organized.
