### ISSUE TITLE
Questions about the modeling in LinkML of the Synonym and Narrower instances

### ISSUE THREAD

**Issue by csnyulas** [who-icatx/whofic-models#17]
What does it mean to have a colon (`:`) after the name of `Synonym` and `Narrower` in the `IndexType` enum, but not having followed with any additional information?
https://github.com/who-icatx/whofic-models/blob/9bca57d6f893b8191eec5ed204c4fd352cd5e248/linkMLmodels/metamodel.yaml#L212-L213

Do we really need the colons there?

Can we have some additional information specified after the colon? If yes, what kind of information?

Does the presence of the colon have any effect on how the name of the instance is generated? (i.e. could be related to why `http://who.int/icd#IndexType#Synonym` contains two hashes?)

**Comment by samsontu** [comment]
I was following the syntax of the example:
![image](https://github.com/who-icatx/whofic-models/assets/1760964/5741f9ef-6139-4b86-8b57-1b077b031b39)
Deleting the colons results in the two string being concatenated into a single instance. Adding "-" in front or ":" at the end results in the same representation of individuals with double #s. I think such URIs are illegal. 
Yes, you can add additional information to enum values, such as descriptions and ontology terms. See 
![image](https://github.com/who-icatx/whofic-models/assets/1760964/c28acdcd-885d-4852-b9b1-e65c13f8e1c6)
