### ISSUE TITLE
referencedEntity should be an object property?

### ISSUE THREAD

**Issue by tudorache** [who-icatx/whofic-models#18]
Currently, referencedEntity is a data property. Shouldn't it be an object property?

**Comment by samsontu** [comment]
If referencedEntity were an object property, then its values would be individuals. I am assuming that IRI references to classes would be treated as strings (uriorcurie in LinkML).

**Comment by samsontu** [comment]
The problem is that IRIs cannot be displayed nicely in webprotege. They cannot be configured for forms either. See for example "Consciousness functions" 
![image](https://github.com/who-icatx/whofic-models/assets/1760964/7e601f79-f24a-4b26-bab5-750c1fbd5086)

**Comment by samsontu** [comment]
referencedEntity may have to be an annotation property, as WebProtege probably does not interpret the entity IRI as a class, and therefore will not display it as such. WebProtege displays ICHI's icfreferences as classes.

**Comment by samsontu** [comment]
I made a version of merged parasitic/mental functions-targets ontology where the referencedEntity is an annotation property and uploaded it to the WHO server, but the configured base exclusions still do not show up on the ICF form.
