### ISSUE TITLE
naming of LinearizationView properties

### ISSUE THREAD

**Issue by samsontu** [who-icatx/whofic-models#22]
Currently the LinearizationView is defined as:
  LinearizationView:
    is_a: ContentModelEntity
    description: >-
      The schema of a linearization
    slots:
      - Id
      - Description
      - rootId
      - LinearizationMode
      - CoreLinId
      - sortingCode
      - defaultIsIncluded
      - defaultIsGrouping
      - defaultIsAuxiliaryAxisChild

The mixed-cases of the properties' first characters follow the examples on the [web page](https://drive.google.com/drive/folders/1ZoeK8vlOBUobrDMwFgvX0tjWIQItR5ye) and in Can's email message. Are these properties names fixed in stone or can they be made consistent with the existing naming convention?

**Comment by tudorache** [comment]
I think we can correct them to use the existing naming conventions.
