### ISSUE TITLE
Linearization model is (partially) replicated in postcoordination model

### ISSUE THREAD

**Issue by csnyulas** [who-icatx/whofic-models#25]
I wonder why we need all this linearization specific model information that is defined in `linkMLmodels/linearizationmodel.yaml` repeated also in the `linkMLmodels/postcoordinationmodel.yaml`
https://github.com/who-icatx/whofic-models/blob/a5abddf3818232fcff6d4ed7d21afe5332c94399/linkMLmodels/postcoordinationmodel.yaml#L69-L160

This seems to be unnecessary and "dangerous", as it can easily lead to inconsistencies.

BTW, the reason I found this was that I wanted to check that we don't have the "unknown" value for the post-coordination.

**Comment by samsontu** [comment]
Fixed
